### ISSUE TITLE
Support Batch Commands

### ISSUE THREAD

**Issue by kienhg96** [RedisLabs/redisgraph.js#3]
https://github.com/NodeRedis/node_redis#clientbatchcommands

**Comment by gkorland** [comment]
can you please extend on the need? which kind of operations are you going to batch?

**Comment by kienhg96** [comment]
Oh, When I create Person A and Person B nodes, I want to make them friends. But redis-graph currently does not support Bidirectional Relationships, I have to make 2 edges: (A)-[:FRIEND]->(B) and (B)-[:FRIEND]->(A). Two individual commands seem OK. According to the node_redis performance tests between batch commands and individual commands (https://github.com/NodeRedis/node_redis#performance), they recommend "This is recommended if you want to execute many commands at once but don't have to rely on transactions".
Moreover, Do you think sometimes we have to use transactions like "client.multi" of node-redis?

**Comment by kienhg96** [comment]
Thank @swilly22, That's good answer. I got it. It solved my problem.
